# TODO: encrypt db password!
server:
    port: 8082
    session:
      timeout: -1
    error:
      whitelabel:
        enabled: false
      path: /errors


spring:
  application:
    name: zno-online

  mvc:
    favicon:
      enabled: true

  jackson:
    serialization.indent_output: true


  mail:
    default-encoding: UTF-8
    protocol: smtp
    username: admin@zno.net.ua
    password: 2`a#KRgzt&\n`"9]
    port: 587
    host: mail.zno.net.ua

  output:
    ansi:
      enabled: detect










