#Server

server:
    port: 8080

# Database
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/zno?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: ENC(EQ8ySN3HxLT61JnHyYqySJ/KvRn3rir7lPddB2sxs6Q=)

    jpa:
        database: mysql
        show-sql: false
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update

    devtools:
        livereload:
            enabled: false

logging:
  level: error
