# TODO: encrypt db password!
server:
    port: 8082

spring:
  application:
    name: zno-online

  mvc:
    favicon:
      enabled: true

  jackson:
    serialization.indent_output: true

  mail:
    default-encoding: UTF-8
    protocol: stmp
#    username:
#    password:

#logging:
#  config: logback-spring.xml










